### ISSUE TITLE
Request Farm Visit 'select date' section ambiguity

### ISSUE THREAD

**Issue by KenStarry** [podii-community/e-poultry#9]
## Date TextField Ambiguity
Here, a user will click on the date section with an aim to schedule a date for the visit. Upon clicking the TextField section, a popup dialog for the calendar will show up.

### Problem Definition
If the user clicks on the cancel option in the calendar dialog, the textfield gains focus and they are free to type anything in the date section. This shouldn't happen.

### Todo

- [x] Redesign the Date textfield to be a button or icon that can direct a user to open the calendar dialog.
- [x] Add dropdown option to choose a farm for which to request the visit.

<p align="center">
<img src="https://github.com/podii-community/e-poultry/assets/82617564/022cae83-978d-45cb-a892-b1292ce7217e"
width="33%"/>
<img src="https://github.com/podii-community/e-poultry/assets/82617564/9878a1b6-719a-47d2-90d0-e92672464e64"
width="33%"/>
<img src="https://github.com/podii-community/e-poultry/assets/82617564/caf98f83-8d0a-468a-8435-c1de84c59b92"
width="33%"/>
</p>

**Comment by KerryMwai** [comment]
The issue was addressed together  on this issue #37

**Comment by KenStarry** [comment]
> The issue was addressed together  on this issue #37 

Did you also implement the Drop-down to select available farms as per design? Coz I was still working on this issue

**Comment by KerryMwai** [comment]
Sorry for that, I had ready the last todo. Will you continue with it

**Comment by KenStarry** [comment]
> Sorry for that, I had not ready the last todo. Will you continue with it?

It's fine, I'll pull your changes then make the adjustment on that section
